spring:
  profiles:
    active: h2

  datasource:
    url: jdbc:mysql://localhost:3306/PETCLINIC_DB?useSSL=false
    # Windows:
    # url: jdbc:mysql://localhost:3306/PETCLINIC_DB?useSSL=false&serverTimezone=UTC
    username: root
    password:

  sql:
    init:
      platform: mysql
      mode: always

logging:
  level:
    root: INFO
  file:
    name: ${user.home}/logs/application.log
  pattern:
    console: "%d{yy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8080